### ISSUE TITLE
老铁，批量一下总是报错的，期待修复

### ISSUE THREAD

**Issue by plmko008** [youki992/VscanPlus#10]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xbc7fc9]

goroutine 39814 [running]:
github.com/youki992/VscanPlus/pocs_go/shiro.aES_CBC_Encrypt({0xc004fcc500?, 0x1e15429?, 0x16?}, {0xc006a00280, 0x70, 0x72})
        /home/ubuntu/zz/pocs_go/shiro/CVE_2016_4437.go:45 +0x49
github.com/youki992/VscanPlus/pocs_go/shiro.CVE_2016_4437({0xc004b39f20, 0x23})
        /home/ubuntu/zz/pocs_go/shiro/CVE_2016_4437.go:85 +0x118
github.com/youki992/VscanPlus/pocs_go.POCcheck({0xc004943f00, 0x4, 0x8?}, {0xc000dd3380, 0x19}, {0xc004b39f20, 0x23}, 0x0)
        /home/ubuntu/zz/pocs_go/go_poc_check.go:42 +0x450
github.com/youki992/VscanPlus/pkg/httpx/runner.(*Runner).analyze(_, _, {_, _}, {_, _}, {_, _}, {0xc003ce1540, 0x19}, ...)
        /home/ubuntu/zz/pkg/httpx/runner/runner.go:1296 +0x4a8c
github.com/youki992/VscanPlus/pkg/httpx/runner.(*Runner).process.func1({0xc003ce1540?, 0xc005c35020?}, {0x15b6349?, 0x0?}, {0xc003ce1540, 0x5})
        /home/ubuntu/zz/pkg/httpx/runner/runner.go:695 +0xfc
created by github.com/youki992/VscanPlus/pkg/httpx/runner.(*Runner).process in goroutine 1
        /home/ubuntu/zz/pkg/httpx/runner/runner.go:693 +0x6c5

**Comment by youki992** [comment]
好的我后续有空修一修

> panic: runtime error: invalid memory address or nil pointer dereference [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xbc7fc9]
> 
> goroutine 39814 [running]: github.com/youki992/VscanPlus/pocs_go/shiro.aES_CBC_Encrypt({0xc004fcc500?, 0x1e15429?, 0x16?}, {0xc006a00280, 0x70, 0x72}) /home/ubuntu/zz/pocs_go/shiro/CVE_2016_4437.go:45 +0x49 github.com/youki992/VscanPlus/pocs_go/shiro.CVE_2016_4437({0xc004b39f20, 0x23}) /home/ubuntu/zz/pocs_go/shiro/CVE_2016_4437.go:85 +0x118 github.com/youki992/VscanPlus/pocs_go.POCcheck({0xc004943f00, 0x4, 0x8?}, {0xc000dd3380, 0x19}, {0xc004b39f20, 0x23}, 0x0) /home/ubuntu/zz/pocs_go/go_poc_check.go:42 +0x450 github.com/youki992/VscanPlus/pkg/httpx/runner.(*Runner).analyze(_, _, {_, _}, {_, _}, {_, _}, {0xc003ce1540, 0x19}, ...) /home/ubuntu/zz/pkg/httpx/runner/runner.go:1296 +0x4a8c github.com/youki992/VscanPlus/pkg/httpx/runner.(*Runner).process.func1({0xc003ce1540?, 0xc005c35020?}, {0x15b6349?, 0x0?}, {0xc003ce1540, 0x5}) /home/ubuntu/zz/pkg/httpx/runner/runner.go:695 +0xfc created by github.com/youki992/VscanPlus/pkg/httpx/runner.(*Runner).process in goroutine 1 /home/ubuntu/zz/pkg/httpx/runner/runner.go:693 +0x6c5

好的我后续有空修一修
