### ISSUE TITLE
老铁你程序关于空指针异常的处理逻辑是不是缺失了

### ISSUE THREAD

**Issue by CrazyDave619** [youki992/VscanPlus#4]
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x18 pc=0x9a02c9]

goroutine 389957 [running]:
github.com/youki992/VscanPlus/pocs_go/shiro.aES_CBC_Encrypt({0xc007cc1970?, 0x1bcd949?, 0x16?}, {0xc0064d2100, 0x70, 0x72})
        C:/Users/13740/Downloads/vscan-main/vscan-main/pocs_go/shiro/CVE_2016_4437.go:45 +0x49
github.com/youki992/VscanPlus/pocs_go/shiro.CVE_2016_4437({0xc00d642840, 0x1c})
        C:/Users/13740/Downloads/vscan-main/vscan-main/pocs_go/shiro/CVE_2016_4437.go:85 +0x125
github.com/youki992/VscanPlus/pocs_go.POCcheck({0xc002d290c0, 0x2, 0x4?}, {0xc003904fc0, 0x1c}, {0xc00d642840, 0x1c}, 0x0)
        C:/Users/13740/Downloads/vscan-main/vscan-main/pocs_go/go_poc_check.go:42 +0x450
github.com/youki992/VscanPlus/pkg/httpx/runner.(*Runner).analyze(_, _, {_, _}, {_, _}, {_, _}, {0xc003ea86c0, 0x1c}, ...)
        C:/Users/13740/Downloads/vscan-main/vscan-main/pkg/httpx/runner/runner.go:1296 +0x57d9
github.com/youki992/VscanPlus/pkg/httpx/runner.(*Runner).process.func1({0xc003ea86c0?, 0xc0061c3200?}, {0x136cb27?, 0x990f6b?}, {0x1388662, 0xa})
        C:/Users/13740/Downloads/vscan-main/vscan-main/pkg/httpx/runner/runner.go:695 +0xf1
created by github.com/youki992/VscanPlus/pkg/httpx/runner.(*Runner).process in goroutine 1
        C:/Users/13740/Downloads/vscan-main/vscan-main/pkg/httpx/runner/runner.go:693 +0x70b

**Comment by youki992** [comment]
是不是请求网站的证书是不安全的，这个后续我看修复一下
